---
- name: Add unit file for REST API
  template:
    src: docker.restapi.service.j2
    dest: /etc/systemd/system/docker.restapi.service
#  notify: reload docker.restapi

- name: Start docker.restapi.service
  systemd:
    state: started
    name: docker.restapi
    enabled: yes
    daemon_reload: yes

# - name: Enable docker.restapi.service
#   systemd:
#     name: docker.restapi
#     enabled: yes
