---
- name: Add unit file for Postgresql
  template:
    src: docker.postgres.service.j2
    dest: /etc/systemd/system/docker.postgres.service
#  notify: reload docker.postgres

- name: Start docker.postgres.service
  systemd:
    state: started
    name: docker.postgres
    enabled: yes
    daemon_reload: yes

# - name: Enable docker.docker.postgres.service
#   systemd:
#     name: docker.docker.postgres
#     enabled: yes
