---
- name: Add unit file for jsonfilter
  template:
    src: docker.jsonfilter.service.j2
    dest: /etc/systemd/system/docker.jsonfilter.service
#  notify: reload docker.jsonfilter

- name: Start docker.jsonfilter.service
  systemd:
    state: started
    name: docker.jsonfilter
    enabled: yes
    daemon_reload: yes